# Generated by Django 4.0.6 on 2022-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_steamadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamrecent',
            name='gameImgURL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='steamrecent',
            name='gameImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
