# Generated by Django 4.0.6 on 2022-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_steamrecent_gameimgurl_alter_steamrecent_gameimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steamname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
